### ISSUE TITLE
Disable scrolling background

### ISSUE THREAD

**Issue by cdancette** [sethmacleod/aerial#1]
Hey ! Is there a simple way to disable scrolling background ? It seems to slow down the page
Thanks

**Comment by sethmacleod** [comment]
Hi @cdancette 

I've added a parameter to `config.toml` to disable the scrolling background.  Redownload the theme and take a look at the [new config file](https://github.com/sethmacleod/aerial/blob/master/exampleSite/config.toml#L10-L11) in the `exampleSite` folder.

**Comment by cdancette** [comment]
Wow that was fast ! @sethmacleod thanks a lot !
